/**
 * Generated by tsnapi — public API snapshot of `@wandelbots/nova-js/experimental/math/index`
 */
// #region Interfaces
export interface PoseData {
  'position'?: Array<number>;
  'orientation'?: Array<number>;
}
// #endregion

// #region Types
export type DeepPoseAugmented<T, Depth extends readonly unknown[] = []> = T extends unknown ? AugmentPosesCore<T, Depth> : never;
export type NovaWithMath = Omit<Nova, "api"> & {
  readonly api: WithAugmentedPoses<Nova["api"]>;
};
export type QuaternionData = {
  w: number;
  x: number;
  y: number;
  z: number;
};
// #endregion

// #region Classes
export declare class Pose implements Pose$1 {
  readonly position: number[];
  readonly orientation: number[];
  constructor(_?: number[], _?: number[]);
  static from(_: Pose$1): Pose;
  static identity(): Pose;
  multiply(_: Pose$1): Pose;
  inverse(): Pose;
  transformPoint(_: number[]): number[];
  isApprox(_: Pose$1, _?: number): boolean;
  toJSON(): Pose$1;
}
export declare class Quaternion implements QuaternionData {
  readonly w: number;
  readonly x: number;
  readonly y: number;
  readonly z: number;
  constructor(_?: number, _?: number, _?: number, _?: number);
  static identity(): Quaternion;
  static fromRotationVector(_: number[]): Quaternion;
  toRotationVector(): number[];
  multiply(_: QuaternionData): Quaternion;
  conjugate(): Quaternion;
  inverse(): Quaternion;
  rotateVector(_: number[]): number[];
  toJSON(): QuaternionData;
}
// #endregion

// #region Functions
export declare function augmentMath(_: Nova): NovaWithMath;
export declare function augmentPoses<T>(_: T): DeepPoseAugmented<T>;
// #endregion