/**
 * Generated by tsnapi — public API snapshot of `@wandelbots/nova-js/experimental/math/index`
 */
// #region Interfaces
export interface PoseData {
  'position'?: Array<number>;
  'orientation'?: Array<number>;
}
// #endregion

// #region Types
export type DeepPoseAugmented<T, Depth extends readonly unknown[] = []> = T extends unknown ? AugmentPosesCore<T, Depth> : never;
export type NovaWithMath = Omit<Nova, "api"> & {
  readonly api: WithAugmentedPoses<Nova["api"]>;
};
export type Quaternion = {
  w: number;
  x: number;
  y: number;
  z: number;
};
// #endregion

// #region Classes
export declare class Pose implements Pose$1 {
  readonly position: number[];
  readonly orientation: number[];
  constructor(_?: number[], _?: number[]);
  static from(_: Pose$1): Pose;
  static identity(): Pose;
  multiply(_: Pose$1): Pose;
  inverse(): Pose;
  transformPoint(_: number[]): number[];
  equals(_: Pose$1, _?: number): boolean;
  toJSON(): Pose$1;
}
// #endregion

// #region Functions
export declare function augmentMath(_: Nova): NovaWithMath;
export declare function augmentPoses<T>(_: T): DeepPoseAugmented<T>;
export declare function axisAngleToQuaternion(_: number[]): Quaternion;
export declare function conjugateQuaternion(_: Quaternion): Quaternion;
export declare function multiplyQuaternions(_: Quaternion, _: Quaternion): Quaternion;
export declare function quaternionToAxisAngle(_: Quaternion): number[];
export declare function rotateVectorByQuaternion(_: Quaternion, _: number[]): number[];
// #endregion