version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "feat"
      prefix-development: "dev"
    versioning-strategy: increase
    groups:
      nova-api:
        patterns:
          - "@wandelbots/nova-api"
      dev-dependencies:
        dependency-type: "development"
      production-dependencies:
        dependency-type: "production"
        exclude-patterns:
          - "@wandelbots/nova-api"
    # Important that the nova-api one gets in there for new NOVA OS releases
    open-pull-requests-limit: 99

  # Github Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 3
