version: 2
updates:
  # nova-api updates when new NOVA OS version is released
  # Will be automatically merged by a github action if tests pass
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "feat"
      prefix-development: "dev"
    versioning-strategy: increase
    allow:
      - dependency-name: "@wandelbots/nova-api"
    open-pull-requests-limit: 99

  # General updates for other dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "fix"
      prefix-development: "dev"
    versioning-strategy: increase
    ignore:
      - dependency-name: "@wandelbots/nova-api"
    groups:
      dev-dependencies:
        dependency-type: "development"
      production-dependencies:
        dependency-type: "production"
    open-pull-requests-limit: 3

  # Github Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 3
