version: 2
updates:
  # Configure dependabot to check daily for updates to @wandelbots/nova-api 
  # The PR then gets automatically merged by a workflow if tests pass
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "feat"
    versioning-strategy: increase
    allow:
      - dependency-name: "@wandelbots/nova-api"
    open-pull-requests-limit: 99
