/**
 * Generated by tsnapi — public API snapshot of `@wandelbots/nova-js`
 */
// #region Types
export type NovaClientConfig = {
  instanceUrl: string | "https://mock.example.com";
  cellId?: string;
  username?: string;
  password?: string;
  accessToken?: string;
} & Omit<Configuration, "isJsonMime" | "basePath">;
export type URLParseOptions = {
  scheme?: "http" | "https";
  defaultScheme?: "http" | "https";
};
// #endregion

// #region Classes
export declare class AutoReconnectingWebsocket extends ReconnectingWebSocket {
  receivedFirstMessage?: MessageEvent;
  targetUrl: string;
  disposed: boolean;
  readonly opts: {
    mock?: MockNovaInstance$1 | MockNovaInstance;
    onDispose?: () => void;
  };
  constructor(_: string, _?: {
    mock?: MockNovaInstance$1 | MockNovaInstance;
    onDispose?: () => void;
  });
  changeUrl(_: string): void;
  sendJson(_: unknown): void;
  dispose(): void;
  opened(): Promise<void>;
  closed(): Promise<void>;
  firstMessage(): Promise<MessageEvent<any>>;
  nextMessage(): Promise<MessageEvent<any>>;
}
export declare class NovaClient {
  readonly api: NovaCellAPIClient;
  readonly config: NovaClientConfigWithDefaults;
  readonly mock?: MockNovaInstance;
  readonly instanceUrl: URL;
  authPromise: Promise<string | null> | null;
  accessToken: string | null;
  constructor(_: NovaClientConfig);
  renewAuthentication(): Promise<void>;
  makeWebsocketURL(_: string): string;
  openReconnectingWebsocket(_: string): AutoReconnectingWebsocket;
  connectMotionStream(_: string): Promise<MotionStreamConnection>;
  connectJogger(_: string): Promise<JoggerConnection>;
  connectMotionGroups(_: string[]): Promise<ConnectedMotionGroup[]>;
  connectMotionGroup(_: string): Promise<ConnectedMotionGroup>;
}
// #endregion

// #region Functions
export declare function degreesToRadians(_: number): number;
export declare function delay(_: number): Promise<unknown>;
export declare function isSameCoordinateSystem(_: string | undefined, _: string | undefined): boolean;
export declare function makeErrorMessage(_: unknown): string;
export declare function makeShortErrorMessage(_: unknown): string;
export declare function makeUrlQueryString(_: Record<string, string>): string;
export declare function parseNovaInstanceUrl(_: string): URL;
export declare function parseUrl(_: string, _?: URLParseOptions): URL;
export declare function poseToWandelscriptString(_: Pick<Pose, "position" | "orientation">): string;
export declare function radiansToDegrees(_: number): number;
export declare function tryParseJson(_: unknown): any;
export declare function tryParseUrl(_: string, _?: URLParseOptions): URL | undefined;
export declare function tryStringifyJson(_: unknown): string | undefined;
// #endregion

// #region Variables
export declare const availableStorage: AvailableStorage;
export declare const getAuth0Config: (instanceUrl: URL) => {
  domain: string;
  clientId: string;
};
export declare const loginWithAuth0: (instanceUrl: URL) => Promise<string | null>;
export declare const XYZ_TO_VECTOR: {
  x: number;
  y: number;
  z: number;
};
// #endregion