/**
 * Generated by tsnapi — public API snapshot of `@wandelbots/nova-js`
 */
// #region Types
export type URLParseOptions = {
  scheme?: "http" | "https";
  defaultScheme?: "http" | "https";
};
// #endregion

// #region Functions
export declare function degreesToRadians(_: number): number;
export declare function delay(_: number): Promise<unknown>;
export declare function isSameCoordinateSystem(_: string | undefined, _: string | undefined): boolean;
export declare function makeErrorMessage(_: unknown): string;
export declare function makeShortErrorMessage(_: unknown): string;
export declare function makeUrlQueryString(_: Record<string, string>): string;
export declare function parseNovaInstanceUrl(_: string): URL;
export declare function parseUrl(_: string, _?: URLParseOptions): URL;
export declare function radiansToDegrees(_: number): number;
export declare function tryParseJson(_: unknown): any;
export declare function tryParseUrl(_: string, _?: URLParseOptions): URL | undefined;
export declare function tryStringifyJson(_: unknown): string | undefined;
// #endregion

// #region Variables
export declare const availableStorage: AvailableStorage;
export declare const getAuth0Config: (instanceUrl: URL) => {
  domain: string;
  clientId: string;
};
export declare const loginWithAuth0: (instanceUrl: URL) => Promise<string | null>;
export declare const XYZ_TO_VECTOR: {
  x: number;
  y: number;
  z: number;
};
// #endregion

// #region Other
export { AutoReconnectingWebsocket }
export { NovaClient }
export { NovaClientConfig }
export { poseToWandelscriptString }
// #endregion