/**
 * Generated by tsnapi — public API snapshot of `@wandelbots/nova-js/v2/index`
 */
// #region Types
export type NovaClientConfig = {
  instanceUrl: string | "https://mock.example.com";
  cellId?: string;
  username?: string;
  password?: string;
  accessToken?: string;
} & Omit<Configuration, "isJsonMime" | "basePath">;
export type WithCellId<T> = { [P in keyof T]: UnwrapAxiosResponseReturn<OmitFirstArg<T[P]>> };
export type WithUnwrappedAxiosResponse<T> = { [P in keyof T]: UnwrapAxiosResponseReturn<T[P]> };
// #endregion

// #region Classes
export declare class NovaCellAPIClient {
  readonly system: WithUnwrappedAxiosResponse<SystemApi>;
  readonly cell: WithUnwrappedAxiosResponse<CellApi>;
  readonly motionGroup: WithCellId<MotionGroupApi>;
  readonly motionGroupModels: WithUnwrappedAxiosResponse<MotionGroupModelsApi>;
  readonly controller: WithCellId<ControllerApi>;
  readonly controllerIOs: WithCellId<ControllerInputsOutputsApi>;
  readonly trajectoryPlanning: WithCellId<TrajectoryPlanningApi>;
  readonly trajectoryExecution: WithCellId<TrajectoryExecutionApi>;
  readonly trajectoryCaching: WithCellId<TrajectoryCachingApi>;
  readonly application: WithCellId<ApplicationApi>;
  readonly applicationGlobal: WithUnwrappedAxiosResponse<ApplicationApi>;
  readonly jogging: WithCellId<JoggingApi>;
  readonly kinematics: WithCellId<KinematicsApi>;
  readonly busInputsOutputs: WithCellId<BUSInputsOutputsApi>;
  readonly virtualController: WithCellId<VirtualControllerApi>;
  readonly virtualControllerBehavior: WithCellId<VirtualControllerBehaviorApi>;
  readonly virtualControllerIOs: WithCellId<VirtualControllerInputsOutputsApi>;
  readonly storeObject: WithCellId<StoreObjectApi>;
  readonly storeCollisionComponents: WithCellId<StoreCollisionComponentsApi>;
  readonly storeCollisionSetups: WithCellId<StoreCollisionSetupsApi>;
  readonly program: WithCellId<ProgramApi>;
  readonly license: WithUnwrappedAxiosResponse<LicenseApi>;
  readonly novaCloud: WithUnwrappedAxiosResponse<NOVACloudApi>;
  readonly robotConfigurations: WithUnwrappedAxiosResponse<RobotConfigurationsApi>;
  readonly version: WithUnwrappedAxiosResponse<VersionApi>;
  readonly session: WithUnwrappedAxiosResponse<SessionApi>;
  readonly cellId: string;
  readonly opts: Configuration & {
    axiosInstance?: AxiosInstance;
    mock?: boolean;
  };
  constructor(_: string, _: Configuration & {
    axiosInstance?: AxiosInstance;
    mock?: boolean;
  });
  private withCellId;
  private withUnwrappedResponsesOnly;
}
export declare class NovaClient {
  readonly api: NovaCellAPIClient;
  readonly config: NovaClientConfigWithDefaults;
  readonly mock?: MockNovaInstance;
  readonly instanceUrl: URL;
  authPromise: Promise<string | null> | null;
  accessToken: string | null;
  constructor(_: NovaClientConfig);
  renewAuthentication(): Promise<void>;
  makeWebsocketURL(_: string): string;
  openReconnectingWebsocket(_: string): AutoReconnectingWebsocket;
}
// #endregion

// #region Functions
export declare function poseToWandelscriptString(_: Pick<Pose, "position" | "orientation">): string;
// #endregion

// #region Re-exports
export * from "@wandelbots/nova-api/v2";
// #endregion

// #region Other
export { Nova }
export { NovaAPIClient }
export { NovaConfig }
// #endregion