/**
 * Generated by tsnapi — public API snapshot of `@wandelbots/nova-js/lib/deprecated/v1/index`
 */
// #region Types
export type CurrentProgram = {
  id?: string;
  wandelscript?: string;
  state?: ProgramState;
};
export type ProgramRunnerLogEntry = {
  timestamp: number;
  message: string;
  level?: "warn" | "error";
};
// #endregion

// #region Enums
export declare enum ProgramState {
  NotStarted = "not started",
  Running = "running",
  Stopped = "stopped",
  Failed = "failed",
  Completed = "completed"
}
// #endregion

// #region Classes
export declare class ProgramStateConnection {
  readonly nova: NovaClient;
  currentProgram: CurrentProgram;
  logs: ProgramRunnerLogEntry[];
  executionState: "idle" | "starting" | "executing" | "stopping";
  currentlyExecutingProgramRunnerId: string | null;
  programStateSocket: AutoReconnectingWebsocket;
  constructor(_: NovaClient);
  handleProgramStateMessage(_: ProgramStateMessage): Promise<void>;
  gotoIdleState(): void;
  executeProgram(_: string, _?: {
    [key: string]: CollectionValue;
  }, _?: MotionStreamConnection): Promise<void>;
  stopProgram(): Promise<void>;
  reset(): void;
  log(_: string): void;
  logError(_: string): void;
}
// #endregion

// #region Functions
export declare function getLatestTrajectories(_: NovaCellAPIClient, _?: number, _?: string): Promise<GetTrajectoryResponse[]>;
// #endregion

// #region Re-exports
export * from "@wandelbots/nova-api/v1";
// #endregion

// #region Other
export { ConnectedMotionGroup }
export { JoggerConnection }
export { JoggerConnectionOpts }
export { MotionGroupOption }
export { MotionStreamConnection }
export { NovaCellAPIClient }
export { NovaClient }
export { NovaClientConfig }
export { poseToWandelscriptString }
export { WithCellId }
export { WithUnwrappedAxiosResponse }
// #endregion