// This file is generated by $ pnpm generate:websocket-endpoints
export const websocketEndpoints = {
  executeJogging: "/cells/{cell}/controllers/{controller}/execution/jogging",
  executeTrajectory:
    "/cells/{cell}/controllers/{controller}/execution/trajectory",
  externalJointsStream:
    "/cells/{cell}/virtual-controllers/{controller}/external-joints-stream",
  streamFreeDrive: "/cells/{cell}/controllers/{controller}/free-drive-stream",
  streamIOValues: "/cells/{cell}/controllers/{controller}/ios/stream",
  streamMotionGroupState:
    "/cells/{cell}/controllers/{controller}/motion-groups/{motion-group}/state-stream",
  streamRobotControllerState:
    "/cells/{cell}/controllers/{controller}/state-stream",
}
