import axios from "axios"
import fs from "node:fs"
import path from "node:path"
import { parse } from "yaml"
import { loadEnvLocal } from "./utils"

async function main() {
  loadEnvLocal()

  const novaUrl = process.env.NOVA
  if (!novaUrl) {
    console.error(
      "NOVA env var is not set. Set it in .env.local or environment.",
    )
    process.exit(1)
  }

  const specUrl = `${novaUrl.replace(/\/+$/, "")}/api/v2/ui/public.openapi.yaml`
  console.log(`Fetching OpenAPI spec from ${specUrl}...`)

  let specText: string
  try {
    const { data } = await axios.get(specUrl, { responseType: "text" })
    specText = data
  } catch (err) {
    console.error(`Failed to fetch OpenAPI spec from ${specUrl}`)
    if (err instanceof Error) console.error(err.message)
    process.exit(1)
  }

  const spec = parse(specText)
  if (!spec?.paths) {
    console.error("No paths found in the OpenAPI spec")
    process.exit(1)
  }

  const endpoints: Record<string, string> = {}

  for (const [urlPath, methods] of Object.entries(
    spec.paths as Record<string, Record<string, Record<string, unknown>>>,
  )) {
    for (const methodDef of Object.values(methods)) {
      if (typeof methodDef !== "object" || !methodDef) continue
      const description = methodDef.description
      if (
        typeof description === "string" &&
        description.includes("> Websocket endpoint")
      ) {
        const operationId = methodDef.operationId
        if (typeof operationId === "string") {
          endpoints[operationId] = urlPath
        }
      }
    }
  }

  if (Object.keys(endpoints).length === 0) {
    console.error("No websocket endpoints found in the OpenAPI spec")
    process.exit(1)
  }

  const sorted = Object.keys(endpoints).sort()
  const entries = sorted.map((id) => `  ${id}: "${endpoints[id]}",`).join("\n")
  const output = `// This file is generated by $ pnpm generate:websocket-endpoints
export const websocketEndpoints = {
${entries}
}
`

  const outPath = path.resolve("src/lib/v2/websocketEndpoints.ts")
  fs.writeFileSync(outPath, output)
  console.log(`Wrote ${sorted.length} websocket endpoints to ${outPath}`)
  for (const id of sorted) {
    console.log(`  ${id}: ${endpoints[id]}`)
  }
}

void main()
