/**
 * Generated by tsnapi — public API snapshot of `@wandelbots/nova-js/experimental/nats/index`
 */
// #region Interfaces
export interface NatsOperationParams {
  "nova.v2.cells.{cell}": {
    cell: string;
  };
  "nova.v2.cells.{cell}.apps.{app}": {
    cell: string;
    app: string;
  };
  "nova.v2.cells.{cell}.programs": {
    cell: string;
  };
  "nova.v2.cells.{cell}.controllers.{controller}": {
    cell: string;
    controller: string;
  };
  "nova.v2.cells.{cell}.status": {
    cell: string;
  };
  "nova.v2.cells.{cell}.cycle": {
    cell: string;
  };
  "nova.v2.system.status": Record<string, never>;
  "nova.v2.cells.{cell}.collision.setups.{setup}": {
    cell: string;
    setup: string;
  };
  "nova.v2.cells.{cell}.bus-ios.status": {
    cell: string;
  };
  "nova.v2.cells.{cell}.bus-ios.ios": {
    cell: string;
  };
  "nova.v2.cells.{cell}.bus-ios.ios.set": {
    cell: string;
  };
  "nova.v2.cells.{cell}.controllers.{controller}.ios.select": {
    cell: string;
    controller: string;
  };
  "nova.v2.cells.{cell}.controllers.{controller}.ios": {
    cell: string;
    controller: string;
  };
  "nova.v2.cells.{cell}.controllers.{controller}.state": {
    cell: string;
    controller: string;
  };
  "nova.v2.cells.{cell}.controllers.{controller}.motion-groups.{motion-group}.description": {
    cell: string;
    controller: string;
    "motion-group": string;
  };
  "nova.v2.events.system.update.started": Record<string, never>;
  "nova.v2.events.system.update.completed": Record<string, never>;
  "nova.v2.events.system.network.status.changed": Record<string, never>;
  "nova.v2.events.cells.{cell}.created": {
    cell: string;
  };
  "nova.v2.events.cells.{cell}.updated": {
    cell: string;
  };
  "nova.v2.events.cells.{cell}.deleted": {
    cell: string;
  };
  "nova.v2.events.cells.{cell}.apps.{app}.created": {
    cell: string;
    app: string;
  };
  "nova.v2.events.cells.{cell}.apps.{app}.updated": {
    cell: string;
    app: string;
  };
  "nova.v2.events.cells.{cell}.apps.{app}.deleted": {
    cell: string;
    app: string;
  };
  "nova.v2.events.cells.{cell}.controllers.{controller}.created": {
    cell: string;
    controller: string;
  };
  "nova.v2.events.cells.{cell}.controllers.{controller}.updated": {
    cell: string;
    controller: string;
  };
  "nova.v2.events.cells.{cell}.controllers.{controller}.deleted": {
    cell: string;
    controller: string;
  };
}
export interface NatsReplyPayloads {
  "nova.v2.cells.{cell}.bus-ios.ios.set": NatsErrorPayload;
  "nova.v2.cells.{cell}.controllers.{controller}.ios.select": NatsErrorPayload;
}
export interface NatsRequestPayloads {
  "nova.v2.cells.{cell}.bus-ios.ios.set": ListIOValuesResponse;
  "nova.v2.cells.{cell}.controllers.{controller}.ios.select": SelectIOs;
}
export interface NatsSubscribePayloads {
  "nova.v2.cells.{cell}": Cell;
  "nova.v2.cells.{cell}.apps.{app}": App;
  "nova.v2.cells.{cell}.programs": ProgramStatus;
  "nova.v2.cells.{cell}.controllers.{controller}": RobotController;
  "nova.v2.cells.{cell}.status": ServiceStatusList;
  "nova.v2.cells.{cell}.cycle": CellCycleEvent;
  "nova.v2.system.status": ServiceStatusList;
  "nova.v2.cells.{cell}.collision.setups.{setup}": CollisionSetup;
  "nova.v2.cells.{cell}.bus-ios.status": BusIOsState;
  "nova.v2.cells.{cell}.bus-ios.ios": ListIOValuesResponse;
  "nova.v2.cells.{cell}.controllers.{controller}.ios": StreamIOValuesResponse;
  "nova.v2.cells.{cell}.controllers.{controller}.state": RobotControllerState;
  "nova.v2.cells.{cell}.controllers.{controller}.motion-groups.{motion-group}.description": MotionGroupDescription;
  "nova.v2.events.system.update.started": SystemUpdateStartedEvent;
  "nova.v2.events.system.update.completed": SystemUpdateCompletedEvent;
  "nova.v2.events.system.network.status.changed": NetworkStatusChangedEvent;
  "nova.v2.events.cells.{cell}.created": CellCreatedEvent;
  "nova.v2.events.cells.{cell}.updated": CellUpdatedEvent;
  "nova.v2.events.cells.{cell}.deleted": CellDeletedEvent;
  "nova.v2.events.cells.{cell}.apps.{app}.created": AppCreatedEvent;
  "nova.v2.events.cells.{cell}.apps.{app}.updated": AppUpdatedEvent;
  "nova.v2.events.cells.{cell}.apps.{app}.deleted": AppDeletedEvent;
  "nova.v2.events.cells.{cell}.controllers.{controller}.created": RobotControllerCreatedEvent;
  "nova.v2.events.cells.{cell}.controllers.{controller}.updated": RobotControllerUpdatedEvent;
  "nova.v2.events.cells.{cell}.controllers.{controller}.deleted": RobotControllerDeletedEvent;
}
// #endregion

// #region Types
export type NatsRequestSubject = keyof NatsRequestPayloads;
export type NatsSubscribeSubject = keyof NatsSubscribePayloads;
export type NovaNatsClientConfig = ConnectionOptions;
// #endregion

// #region Classes
export declare class NovaNatsClient {
  readonly config: NovaNatsClientConfig;
  connection: NatsConnection | null;
  constructor(_: NovaNatsClientConfig);
  connect(): Promise<NatsConnection>;
  close(): Promise<void>;
  subscribe<K extends NatsSubscribeSubject>(_: K, _: NatsOperationParams[K], _: (_: NatsSubscribePayloads[K], _: Msg) => void): Promise<() => void>;
  request<K extends NatsRequestSubject>(_: K, _: NatsOperationParams[K], _: NatsRequestPayloads[K], _?: {
    timeout?: number;
  }): Promise<NatsReplyPayloads[K]>;
}
// #endregion