/**
 * Generated by tsnapi — public API snapshot of `@wandelbots/nova-js/test-utils/index`
 */
// #region Interfaces
export interface InstanceProvider {
  readonly name: string;
  reserveInstance(_: ReserveInstanceOptions): Promise<ReservedInstance>;
  extendInstance?(_: string, _: number): Promise<boolean>;
  releaseInstance?(_: string): Promise<void>;
}
// #endregion

// #region Types
export type K8sWaboRunProviderOptions = {
  baseUrl?: string;
  https?: boolean;
};
export type PatchLocalEnvOptions = {
  path?: string;
  mutateProcessEnv?: boolean;
  log?: (..._: unknown[]) => void;
};
export type PortalProviderOptions = {
  baseUrl?: string;
  accessToken: string;
};
export type ReservedInstance = {
  instanceUrl: string;
  instanceId?: string;
  kubeconfig?: string;
};
export type ReserveInstanceOptions = {
  lifetimeMins: number;
  comment?: string;
  installServiceManager?: boolean;
  serviceManagerVersion?: string;
};
export type TestDeployOptions = {
  provider: InstanceProvider;
  instanceLifetimeMins?: number;
  cellId?: string;
  accessToken?: string;
  existingInstance?: string;
  existingInstanceStrategy?: "reuse" | "replace";
  comment?: string;
  installServiceManager?: boolean;
  serviceManagerVersion?: string;
  waitForInstance?: WaitForInstanceOptions | false;
  setupCell?: (_: Nova, _: string) => Promise<void>;
  skipSetupIfControllersExist?: boolean;
  onDeployed?: (_: Nova, _: string) => Promise<void>;
  writeEnv?: WriteEnvOptions | false;
  kubeconfigPath?: string | false;
  log?: (..._: unknown[]) => void;
};
export type TestDeployResult = {
  nova: Nova;
  instanceUrl: string;
  instanceId?: string;
  cellId: string;
  reused: boolean;
};
export type WaitForInstanceOptions = WaitOptions & {
  requiredServices?: string[];
};
export type WaitOptions = {
  timeoutMs?: number;
  pollIntervalMs?: number;
  log?: (..._: unknown[]) => void;
};
export type WriteEnvOptions = {
  path?: string;
  instanceUrlVar?: string;
  instanceUrlAsHostname?: boolean;
  instanceIdVar?: string | false;
  cellIdVar?: string | false;
};
// #endregion

// #region Classes
export declare class K8sWaboRunProvider implements InstanceProvider {
  readonly name = "k8s.wabo.run";
  readonly baseUrl: string;
  readonly https: boolean;
  constructor(_?: K8sWaboRunProviderOptions);
  reserveInstance(_: ReserveInstanceOptions): Promise<ReservedInstance>;
  extendInstance(_: string, _: number): Promise<boolean>;
  releaseInstance(_: string): Promise<void>;
}
export declare class PortalProvider implements InstanceProvider {
  readonly name = "portal";
  readonly baseUrl: string;
  readonly accessToken: string;
  constructor(_: PortalProviderOptions);
  reserveInstance(_: ReserveInstanceOptions): Promise<ReservedInstance>;
}
// #endregion

// #region Functions
export declare function patchLocalEnv(_: Record<string, string>, _?: PatchLocalEnvOptions): Promise<void>;
export declare function runTestDeploy(_: TestDeployOptions): Promise<void>;
export declare function testDeploy(_: TestDeployOptions): Promise<TestDeployResult>;
export declare function toSandboxName(_: string | undefined): string;
export declare function waitForCellStartup(_: Nova, _: string, _?: WaitOptions): Promise<void>;
export declare function waitForNovaInstanceStartup(_: Nova, _?: WaitForInstanceOptions): Promise<void>;
export declare function waitForRobotControllerStartup(_: Nova, _: string, _?: WaitOptions): Promise<void>;
// #endregion